#!/usr/bin/env bash
# Prepare a fresh Rakazo guest: Docker, the checkout, deployment files and backups.
#
# Run as root inside the guest, from a copy of this directory. It does not start
# the stack; `sudo -u rakazo /opt/rakazo/ops/deploy.sh up` does that afterwards.
#
# Usage:
#   bootstrap-guest.sh --host <address> --vars <deployment.env> --ca-cert <file> < model-gateway-key
#
#   --host      the one address the deployment is served on
#   --vars      deployment settings that are not secrets and not derived from --host
#               (model gateway URL and lists, default model, computer limits, mounts)
#   --ca-cert   CA certificate the api and worker trust; the sandbox overlay binds it
#               unconditionally, so it must be a real file even with no MCP server using it
#   stdin       the model gateway API key, kept off the command line
#
# Environment:
#   RAKAZO_FORK         required, the `owner/repo` the checkout is cloned from
#   RAKAZO_BASE_BRANCH  branch to clone, default deploy/hds
#
# Safe to re-run: it never overwrites an existing .env or checkout.
set -euo pipefail

HOST="" VARS="" CA_CERT=""
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# The fork is required rather than defaulted: this file is public, so it must not
# name an account, and a wrong default would silently clone somebody else's tree.
RAKAZO_FORK="${RAKAZO_FORK:-}"
RAKAZO_BASE_BRANCH="${RAKAZO_BASE_BRANCH:-deploy/hds}"
CHECKOUT=/opt/rakazo
LOCAL_DIR=/opt/rakazo-local
BOTWORK=/var/rakazo/botwork

die() { echo "bootstrap-guest: $*" >&2; exit 1; }

while [[ $# -gt 0 ]]; do
  case "$1" in
    --host) HOST="$2"; shift 2 ;;
    --vars) VARS="$2"; shift 2 ;;
    --ca-cert) CA_CERT="$2"; shift 2 ;;
    *) die "unknown argument: $1" ;;
  esac
done

[[ $EUID -eq 0 ]] || die "run as root"
[[ -n "$HOST" && -f "$VARS" && -f "$CA_CERT" ]] || die "--host, --vars <file> and --ca-cert <file> are required"
[[ "$RAKAZO_FORK" =~ ^[A-Za-z0-9._-]+/[A-Za-z0-9._-]+$ ]] \
  || die "set RAKAZO_FORK to the owner/repo to clone, for example RAKAZO_FORK=acme/rakazo"
id rakazo >/dev/null 2>&1 || die "user rakazo is missing; was the guest built from cloud-init.yaml?"

MODEL_KEY=""
if [[ ! -f "$CHECKOUT/.env" ]]; then
  [[ -t 0 ]] && die "pipe the model gateway API key on stdin"
  IFS= read -r MODEL_KEY || true
  [[ -n "$MODEL_KEY" ]] || die "empty model gateway API key on stdin"
  # The key is written into the generated .env as a single-quoted value, which is
  # what stops Compose interpolating a $ in it. A single quote in the key itself
  # cannot be represented inside that form, so refuse it rather than mangle it.
  [[ "$MODEL_KEY" != *"'"* ]] || die "the model gateway API key contains a single quote, which cannot be written to .env"
fi

# Everything this script writes into .env. The vars file may not set any of these
# keys, so a secret can never be supplied by hand and a host-derived URL can never
# disagree with --host. Variables the compose files require are also listed for CI in
# ops/ci/compose-check.env; when upstream adds one, update both.
OWNED_ENV="$(cat <<EOF
# Generated by ops/host/bootstrap-guest.sh on $(date -u +%FT%TZ). Vault a copy.
NODE_ENV=production
LOG_LEVEL=info
RAKAZO_HOST=${HOST}
BETTER_AUTH_URL=https://${HOST}
WEB_ORIGIN=https://${HOST}
API_URL=https://${HOST}/api
CADDYFILE_PATH=${LOCAL_DIR}/Caddyfile
POSTGRES_USER=rakazo
POSTGRES_DB=rakazo
POSTGRES_PASSWORD=$(openssl rand -hex 32)
BETTER_AUTH_SECRET=$(openssl rand -hex 32)
ENCRYPTION_KEY=$(openssl rand -hex 32)
SANDBOX_SUPERVISOR_TOKEN=$(openssl rand -hex 32)
SCREEN_PROXY_SECRET=$(openssl rand -hex 32)
# Signup policy only seeds the api's first start; after that the stored deployment
# settings are authoritative and editing these lines changes nothing. An allowlist
# without email delivery refuses every signup.
SIGNUPS_ENABLED=false
SIGNUP_ALLOWLIST=
SANDBOX_PROVIDER=docker
SANDBOX_SUPERVISOR_URL=http://supervisor:7091
DATA_DIR=/data
AGENT_RUNTIME=pi
WAKEUP_DRIVER=graphile
RAKAZO_IMAGE_TAG=local
RAKAZO_UPDATER_URL=
GIT_SHA=
RAKAZO_LOCAL_MODELS_API_KEY='${MODEL_KEY}'
EOF
)"
while IFS= read -r key; do
  if grep -Eq "^[[:space:]]*${key}=" "$VARS"; then
    die "$VARS sets $key, which this script owns"
  fi
done < <(sed -nE 's/^([A-Z_]+)=.*/\1/p' <<<"$OWNED_ENV")

# Docker's second built-in address pool is 192.168.0.0/16. The supervisor creates a
# network per bot, and once the 172.x pool runs out Docker starts handing out LAN
# ranges and black-holes real hosts. Written before Docker is installed, so the
# daemon's first start already uses the pinned pool.
if [[ ! -f /etc/docker/daemon.json ]]; then
  install -d -m 755 /etc/docker
  cat > /etc/docker/daemon.json <<'JSON'
{
  "default-address-pools": [{ "base": "10.200.0.0/14", "size": 24 }],
  "log-driver": "local"
}
JSON
  if systemctl is-active --quiet docker; then
    systemctl restart docker
  fi
fi

# Docker from Docker's own apt repository, the source the existing deployment uses.
if ! command -v docker >/dev/null 2>&1; then
  install -d -m 755 /etc/apt/keyrings
  curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc
  chmod 644 /etc/apt/keyrings/docker.asc
  # shellcheck source=/dev/null
  codename="$(. /etc/os-release && echo "$VERSION_CODENAME")"
  echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian ${codename} stable" \
    > /etc/apt/sources.list.d/docker.list
  apt-get update -q
  DEBIAN_FRONTEND=noninteractive apt-get install -yq \
    docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
fi
usermod -aG docker rakazo

if [[ ! -d "$CHECKOUT/.git" ]]; then
  install -d -o rakazo -g rakazo -m 755 "$CHECKOUT"
  sudo -u rakazo git clone --branch "$RAKAZO_BASE_BRANCH" "https://github.com/${RAKAZO_FORK}.git" "$CHECKOUT"
fi

install -d -m 755 "$BOTWORK"
install -d -o rakazo -g rakazo -m 755 "$LOCAL_DIR"
install -o rakazo -g rakazo -m 644 "$HERE/Caddyfile.ip" "$LOCAL_DIR/Caddyfile"
install -d -o rakazo -g rakazo -m 755 "$CHECKOUT/ops/certs"
install -o rakazo -g rakazo -m 644 "$CA_CERT" "$CHECKOUT/ops/certs/qmd-gateway.crt"

if [[ ! -f "$CHECKOUT/.env" ]]; then
  tmp="$(mktemp)"
  {
    printf '%s\n' "$OWNED_ENV"
    echo "# Deployment settings from $(basename "$VARS")"
    grep -Ev '^[[:space:]]*(#|$)' "$VARS"
  } > "$tmp"
  install -o rakazo -g rakazo -m 600 "$tmp" "$CHECKOUT/.env"
  rm -f "$tmp"
fi

install -m 755 "$CHECKOUT/ops/backup-prod.sh" /usr/local/sbin/rakazo-backup
install -m 644 "$CHECKOUT/infra/systemd/rakazo-backup.service" /etc/systemd/system/rakazo-backup.service
install -m 644 "$CHECKOUT/infra/systemd/rakazo-backup.timer" /etc/systemd/system/rakazo-backup.timer
systemctl daemon-reload
systemctl enable --now rakazo-backup.timer

echo "Guest ready. Next: sudo -u rakazo ${CHECKOUT}/ops/deploy.sh up"
