#!/usr/bin/env bash
# Prepare a fresh Rakazo guest: Docker, the checkout, deployment files and backups.
#
# Run as root inside the guest, from a copy of this directory. It does not start
# the stack; `sudo -u rakazo /opt/rakazo/ops/deploy.sh up` does that afterwards.
#
# Usage:
#   bootstrap-guest.sh --host <address> --vars <deployment.env> --ca-cert <file> < model-gateway-key
#
#   --host      the one address the deployment is served on
#   --vars      deployment settings that are not secrets and not derived from --host
#               (model gateway URL and lists, default model, computer limits, mounts)
#   --ca-cert   CA certificate the api and worker trust; the sandbox overlay binds it
#               unconditionally, so it must be a real file even with no MCP server using it
#   stdin       the model gateway API key, kept off the command line
#
# Safe to re-run: it never overwrites an existing .env or checkout.
set -euo pipefail

HOST="" VARS="" CA_CERT=""
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_URL="https://github.com/hyamie/rakazo.git"
BRANCH="deploy/hds"
CHECKOUT=/opt/rakazo
LOCAL_DIR=/opt/rakazo-local
BOTWORK=/var/rakazo/botwork

die() { echo "bootstrap-guest: $*" >&2; exit 1; }

while [[ $# -gt 0 ]]; do
  case "$1" in
    --host) HOST="$2"; shift 2 ;;
    --vars) VARS="$2"; shift 2 ;;
    --ca-cert) CA_CERT="$2"; shift 2 ;;
    *) die "unknown argument: $1" ;;
  esac
done

[[ $EUID -eq 0 ]] || die "run as root"
[[ -n "$HOST" && -f "$VARS" && -f "$CA_CERT" ]] || die "--host, --vars <file> and --ca-cert <file> are required"
id rakazo >/dev/null 2>&1 || die "user rakazo is missing; was the guest built from cloud-init.yaml?"

# Keys this script writes itself. The vars file may not set them, so a secret can
# never be supplied by hand and a host-derived URL can never disagree with --host.
OWNED_KEYS=(NODE_ENV LOG_LEVEL BETTER_AUTH_URL API_URL WEB_ORIGIN RAKAZO_HOST CADDYFILE_PATH
  POSTGRES_USER POSTGRES_PASSWORD POSTGRES_DB BETTER_AUTH_SECRET ENCRYPTION_KEY
  SANDBOX_SUPERVISOR_TOKEN SCREEN_PROXY_SECRET SIGNUPS_ENABLED SIGNUP_ALLOWLIST
  SANDBOX_PROVIDER SANDBOX_SUPERVISOR_URL DATA_DIR AGENT_RUNTIME WAKEUP_DRIVER
  RAKAZO_IMAGE RAKAZO_IMAGE_TAG RAKAZO_UPDATER_URL GIT_SHA RAKAZO_LOCAL_MODELS_API_KEY)
for key in "${OWNED_KEYS[@]}"; do
  if grep -Eq "^[[:space:]]*${key}=" "$VARS"; then
    die "$VARS sets $key, which this script owns"
  fi
done

MODEL_KEY=""
if [[ ! -f "$CHECKOUT/.env" ]]; then
  [[ -t 0 ]] && die "pipe the model gateway API key on stdin"
  IFS= read -r MODEL_KEY || true
  [[ -n "$MODEL_KEY" ]] || die "empty model gateway API key on stdin"
fi

# Docker from Docker's own apt repository, the source the existing deployment uses.
if ! command -v docker >/dev/null 2>&1; then
  install -d -m 755 /etc/apt/keyrings
  curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc
  chmod 644 /etc/apt/keyrings/docker.asc
  codename="$(. /etc/os-release && echo "$VERSION_CODENAME")"
  echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian ${codename} stable" \
    > /etc/apt/sources.list.d/docker.list
  apt-get update -q
  DEBIAN_FRONTEND=noninteractive apt-get install -yq \
    docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
fi

# Docker's second built-in address pool is 192.168.0.0/16. The supervisor creates a
# network per bot, and once the 172.x pool runs out Docker starts handing out LAN
# ranges and black-holes real hosts. Pin the pool before any network exists.
if [[ ! -f /etc/docker/daemon.json ]]; then
  cat > /etc/docker/daemon.json <<'JSON'
{
  "default-address-pools": [{ "base": "10.200.0.0/14", "size": 24 }],
  "log-driver": "local"
}
JSON
  systemctl restart docker
fi
usermod -aG docker rakazo

if [[ ! -d "$CHECKOUT/.git" ]]; then
  install -d -o rakazo -g rakazo -m 755 "$CHECKOUT"
  sudo -u rakazo git clone --branch "$BRANCH" "$REPO_URL" "$CHECKOUT"
fi

install -d -m 755 "$BOTWORK"
install -d -o rakazo -g rakazo -m 755 "$LOCAL_DIR"
install -o rakazo -g rakazo -m 644 "$HERE/Caddyfile.ip" "$LOCAL_DIR/Caddyfile"
install -d -o rakazo -g rakazo -m 755 "$CHECKOUT/ops/certs"
install -o rakazo -g rakazo -m 644 "$CA_CERT" "$CHECKOUT/ops/certs/qmd-gateway.crt"

if [[ ! -f "$CHECKOUT/.env" ]]; then
  umask 077
  tmp="$(mktemp)"
  {
    echo "# Generated by ops/host/bootstrap-guest.sh on $(date -u +%FT%TZ). Vault a copy."
    echo "NODE_ENV=production"
    echo "LOG_LEVEL=info"
    echo "RAKAZO_HOST=${HOST}"
    echo "BETTER_AUTH_URL=https://${HOST}"
    echo "WEB_ORIGIN=https://${HOST}"
    echo "API_URL=https://${HOST}/api"
    echo "CADDYFILE_PATH=${LOCAL_DIR}/Caddyfile"
    echo "POSTGRES_USER=rakazo"
    echo "POSTGRES_DB=rakazo"
    echo "POSTGRES_PASSWORD=$(openssl rand -hex 32)"
    echo "BETTER_AUTH_SECRET=$(openssl rand -hex 32)"
    echo "ENCRYPTION_KEY=$(openssl rand -hex 32)"
    echo "SANDBOX_SUPERVISOR_TOKEN=$(openssl rand -hex 32)"
    echo "SCREEN_PROXY_SECRET=$(openssl rand -hex 32)"
    echo "# Closed until the operator names the first account's address."
    echo "SIGNUPS_ENABLED=false"
    echo "SIGNUP_ALLOWLIST="
    echo "SANDBOX_PROVIDER=docker"
    echo "SANDBOX_SUPERVISOR_URL=http://supervisor:7091"
    echo "DATA_DIR=/data"
    echo "AGENT_RUNTIME=pi"
    echo "WAKEUP_DRIVER=graphile"
    echo "RAKAZO_IMAGE=ghcr.io/elie222/rakazo/app"
    echo "RAKAZO_IMAGE_TAG=local"
    echo "RAKAZO_UPDATER_URL="
    echo "GIT_SHA="
    echo "RAKAZO_LOCAL_MODELS_API_KEY=${MODEL_KEY}"
    echo "# Deployment settings from $(basename "$VARS")"
    grep -Ev '^[[:space:]]*(#|$)' "$VARS"
  } > "$tmp"
  install -o rakazo -g rakazo -m 600 "$tmp" "$CHECKOUT/.env"
  rm -f "$tmp"
  umask 022
fi

install -m 755 "$CHECKOUT/ops/backup-prod.sh" /usr/local/sbin/rakazo-backup
install -m 644 "$CHECKOUT/infra/systemd/rakazo-backup.service" /etc/systemd/system/rakazo-backup.service
install -m 644 "$CHECKOUT/infra/systemd/rakazo-backup.timer" /etc/systemd/system/rakazo-backup.timer
systemctl daemon-reload
systemctl enable --now rakazo-backup.timer

echo "Guest ready. Next: sudo -u rakazo ${CHECKOUT}/ops/deploy.sh up"
